"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
import TopicSelector, { Topic, TopicSelection } from "@/components/TopicSelector";

type RolePreference = "seek_help" | "give_help" | "both";

function looksAutoGenerated(name: string): boolean {
  return /^[A-Z][a-z]+[A-Z][a-z]+\d{3,4}$/.test(name.trim());
}

function looksLikeItMatchesEmail(name: string, emailValue: string): boolean {
  const cleanName = name.toLowerCase().replace(/[^a-z0-9]/g, "");
  const localPart = emailValue.split("@")[0]?.toLowerCase().replace(/[^a-z0-9]/g, "") ?? "";
  if (cleanName.length < 3 || localPart.length < 3) return false;
  return localPart.includes(cleanName) || cleanName.includes(localPart);
}

export default function OnboardingPage() {
  const router = useRouter();
  const supabase = createClient();

  const [displayName, setDisplayName] = useState("");
  const [generatingName, setGeneratingName] = useState(false);
  const [userEmail, setUserEmail] = useState("");
  const [role, setRole] = useState<RolePreference>("seek_help");
  const [topics, setTopics] = useState<Topic[]>([]);
  const [selections, setSelections] = useState<TopicSelection>({});
  const [loadingInitial, setLoadingInitial] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    (async () => {
      const { data: userRes } = await supabase.auth.getUser();
      const userId = userRes.user?.id;
      setUserEmail(userRes.user?.email ?? "");
      if (!userId) {
        setLoadingInitial(false);
        return;
      }

      const { data: topicRows } = await supabase
        .from("topics")
        .select("id, name")
        .order("sort_order");
      setTopics(topicRows ?? []);

      const { data: profileRow } = await supabase
        .from("profiles")
        .select("display_name, role_preference")
        .eq("id", userId)
        .single();

      if (profileRow) {
        setDisplayName(profileRow.display_name ?? "");
        setRole(profileRow.role_preference as RolePreference);
      }

      const { data: existingTopics } = await supabase
        .from("user_topics")
        .select("topic_id, kind, rating")
        .eq("user_id", userId);

      if (existingTopics) {
        const prefilled: TopicSelection = {};
        existingTopics.forEach((row) => {
          prefilled[row.topic_id] = { kind: row.kind, rating: row.rating };
        });
        setSelections(prefilled);
      }

      setLoadingInitial(false);
    })();
  }, []);

  async function handleGenerateName() {
    setGeneratingName(true);
    const { data, error: rpcError } = await supabase.rpc("generate_anon_display_name");
    if (!rpcError && data) {
      setDisplayName(data as string);
    }
    setGeneratingName(false);
  }

  async function handleSubmit() {
    setError(null);

    if (displayName.trim().length === 0) {
      setError("Please enter a display name.");
      return;
    }

    setSaving(true);

    const { data: userRes } = await supabase.auth.getUser();
    const userId = userRes.user?.id;
    if (!userId) {
      setError("Your session expired. Please log in again.");
      setSaving(false);
      return;
    }

    const { error: profileError } = await supabase
      .from("profiles")
      .update({ display_name: displayName.trim(), role_preference: role, onboarded: true })
      .eq("id", userId);

    if (profileError) {
      setError(profileError.message);
      setSaving(false);
      return;
    }

    // Replace this user's topic selections wholesale on every save, so
    // a topic they un-select while editing doesn't linger in the
    // database from a previous visit to this page.
    const { error: deleteError } = await supabase
      .from("user_topics")
      .delete()
      .eq("user_id", userId);

    if (deleteError) {
      setError(deleteError.message);
      setSaving(false);
      return;
    }

    const rows = Object.entries(selections)
      .filter(([, v]) => v.kind !== null)
      .map(([topicId, v]) => ({
        user_id: userId,
        topic_id: Number(topicId),
        kind: v.kind,
        rating: v.rating,
      }));

    if (rows.length > 0) {
      const { error: topicsError } = await supabase.from("user_topics").insert(rows);
      if (topicsError) {
        setError(topicsError.message);
        setSaving(false);
        return;
      }
    }

    router.push("/lobby");
  }

  const showNameWarning =
    displayName.trim().length > 0 &&
    (!looksAutoGenerated(displayName) || looksLikeItMatchesEmail(displayName, userEmail));

  if (loadingInitial) {
    return (
      <main className="min-h-screen flex items-center justify-center">
        <p className="text-ink-500">Loading…</p>
      </main>
    );
  }

  return (
    <main className="min-h-screen px-6 py-12 flex justify-center">
      <div className="w-full max-w-2xl space-y-8">
        <div>
          <h1 className="font-display text-2xl text-ink-900">A bit about you</h1>
          <p className="text-ink-500 text-sm mt-1">
            This helps us pair you with the right person. You can change this any time.
          </p>
        </div>

        <section className="card">
          <h2 className="font-medium text-ink-900 mb-1">Your display name</h2>
          <p className="text-ink-500 text-sm mb-3">
            This is the only name the person you're matched with will ever see.
          </p>
          <div className="flex gap-2">
            <input
              required
              value={displayName}
              onChange={(e) => setDisplayName(e.target.value)}
              className="input-field flex-1"
              placeholder="e.g. QuietRiver482"
            />
            <button
              type="button"
              onClick={handleGenerateName}
              disabled={generatingName}
              className="btn-secondary whitespace-nowrap"
            >
              {generatingName ? "…" : "Generate"}
            </button>
          </div>
          {showNameWarning && (
            <p className="text-xs text-clay-600 mt-2">
              This looks like it might be a real name — change it above before continuing.
            </p>
          )}
        </section>

        <section className="card">
          <h2 className="font-medium text-ink-900 mb-3">
            Hi {displayName || "there"}, what are you here for?
          </h2>
          <div className="flex flex-col gap-2">
            {[
              { value: "seek_help", label: "I want someone to talk to" },
              { value: "give_help", label: "I want to support someone else" },
              { value: "both", label: "Either is fine" },
            ].map((opt) => (
              <label
                key={opt.value}
                className={`flex items-center gap-3 border rounded-card px-4 py-3 cursor-pointer ${
                  role === opt.value ? "border-sage-500 bg-sage-100" : "border-ink-500/15"
                }`}
              >
                <input
                  type="radio"
                  name="role"
                  value={opt.value}
                  checked={role === opt.value}
                  onChange={() => setRole(opt.value as RolePreference)}
                />
                <span className="text-sm text-ink-900">{opt.label}</span>
              </label>
            ))}
          </div>
        </section>

        <section className="card">
          <h2 className="font-medium text-ink-900 mb-1">Your strengths and what you're working on</h2>
          <p className="text-ink-500 text-sm mb-2">
            Mark a topic as a <strong className="font-bold text-sage-600">Strength</strong> if you
            feel equipped to support someone there, or{" "}
            <strong className="font-bold text-gold-500">Working on it</strong> if it's something
            you're personally finding hard right now.
          </p>
          <p className="text-ink-500 text-sm mb-4">
            For a <strong className="font-bold text-sage-600">Strength</strong>, 1 means you're
            fairly confident there and 5 means you're very strong in it. For{" "}
            <strong className="font-bold text-gold-500">Working on it</strong>, 1 means you're
            struggling a little and 5 means you're struggling a lot.
          </p>
          <TopicSelector topics={topics} selections={selections} onChange={setSelections} />
        </section>

        {error && <p className="text-clay-600 text-sm">{error}</p>}

        <button onClick={handleSubmit} disabled={saving} className="btn-primary w-full">
          {saving ? "Saving…" : "Continue"}
        </button>
      </div>
    </main>
  );
}