"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faEye, faEyeSlash } from "@fortawesome/free-solid-svg-icons";
import Link from "next/link";

function looksAutoGenerated(name: string): boolean {
  return /^[A-Z][a-z]+[A-Z][a-z]+\d{3,4}$/.test(name.trim());
}

function looksLikeItMatchesEmail(name: string, emailValue: string): boolean {
  const cleanName = name.toLowerCase().replace(/[^a-z0-9]/g, "");
  const localPart = emailValue.split("@")[0]?.toLowerCase().replace(/[^a-z0-9]/g, "") ?? "";
  if (cleanName.length < 3 || localPart.length < 3) return false;
  return localPart.includes(cleanName) || cleanName.includes(localPart);
}

export default function SignupPage() {
  const router = useRouter();
  const supabase = createClient();

  const [displayName, setDisplayName] = useState("");
  const [generatingName, setGeneratingName] = useState(false);
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [showPassword, setShowPassword] = useState(false);
  const [showConfirmPassword, setShowConfirmPassword] = useState(false);
  const [acknowledged, setAcknowledged] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [confirmationSent, setConfirmationSent] = useState(false);

  async function handleGenerateName() {
    setGeneratingName(true);
    const { data, error: rpcError } = await supabase.rpc("generate_anon_display_name");
    if (!rpcError && data) {
      setDisplayName(data as string);
    }
    setGeneratingName(false);
  }

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    setError(null);

    if (password !== confirmPassword) {
      setError("Passwords do not match.");
      return;
    }

    if (!acknowledged) {
      setError(
        "Please confirm you've read the safety notice before continuing."
      );
      return;
    }

    setLoading(true);

    const { error: signUpError } = await supabase.auth.signUp({
      email,
      password,
      options: {
        data: { display_name: displayName },
      },
    });

    setLoading(false);

    if (signUpError) {
      setError(signUpError.message);
      return;
    }

    setConfirmationSent(true);
  }

  async function handleGoogleSignIn() {
    await supabase.auth.signInWithOAuth({
      provider: "google",
      options: { redirectTo: `${window.location.origin}/auth/callback` },
    });
  }

  const showNameWarning =
    displayName.trim().length > 0 &&
    (!looksAutoGenerated(displayName) || looksLikeItMatchesEmail(displayName, email));

  if (confirmationSent) {
    return (
      <main className="min-h-screen flex items-center justify-center px-6 py-12">
        <div className="card w-full max-w-md text-center">
          <h1 className="font-display text-2xl text-ink-900 mb-2">Check your email</h1>
          <p className="text-ink-700 text-sm">
            We've sent a confirmation link to <span className="font-medium">{email}</span>.
            Click it, then come back here and log in.
          </p>
        </div>
      </main>
    );
  }

  return (
    <main className="min-h-screen flex items-center justify-center px-6 py-12">
      <div className="card w-full max-w-md">
        <h1 className="font-display text-2xl text-ink-900 mb-1">
          Create your account
        </h1>

        <p className="text-ink-500 text-sm mb-6">
          Use a made-up display name, not your real name. The person you're
          matched with will only ever see this name, never your real one.
        </p>

        <div className="bg-gold-100 border border-gold-500/30 rounded-card p-4 mb-6 text-sm text-ink-700">
          <p className="font-medium text-ink-900 mb-1">
            Before you continue
          </p>

          <p>
            Never share your phone number, your exact location, or other
            identifying details with people you're matched with here. Keep the
            conversation on this app.
          </p>
        </div>

        <button onClick={handleGoogleSignIn} className="btn-secondary w-full mb-5">
          Continue with Google
        </button>
        <div className="flex items-center gap-3 mb-5 text-xs text-ink-500">
          <div className="h-px bg-ink-500/15 flex-1" />
          or use email
          <div className="h-px bg-ink-500/15 flex-1" />
        </div>

        <form onSubmit={handleSubmit} className="space-y-4">
          <div>
            <label className="block text-sm font-medium text-ink-700 mb-1">
              Display name{" "}
              <span className="font-normal text-clay-600">
                (don't enter your real name — the person you talk to will see this)
              </span>
            </label>

            <div className="flex gap-2">
              <input
                required
                value={displayName}
                onChange={(e) => setDisplayName(e.target.value)}
                className="input-field flex-1"
                placeholder="e.g. QuietRiver482"
              />
              <button
                type="button"
                onClick={handleGenerateName}
                disabled={generatingName}
                className="btn-secondary whitespace-nowrap"
              >
                {generatingName ? "…" : "Generate"}
              </button>
            </div>
            {showNameWarning && (
              <p className="text-xs text-clay-600 mt-2">
                This looks like it might be a real name — change it above before continuing.
              </p>
            )}
          </div>

          <div>
            <label className="block text-sm font-medium text-ink-700 mb-1">
              Email
            </label>

            <input
              required
              type="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              className="input-field"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-ink-700 mb-1">
              Password
            </label>

            <div className="relative">
              <input
                required
                minLength={8}
                type={showPassword ? "text" : "password"}
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                className="input-field pr-12"
              />

              <button
                type="button"
                onClick={() => setShowPassword((prev) => !prev)}
                className="absolute right-3 top-1/2 -translate-y-1/2 text-ink-500 hover:text-ink-800 transition-colors"
                aria-label={showPassword ? "Hide password" : "Show password"}
              >
                <FontAwesomeIcon
                  icon={showPassword ? faEye : faEyeSlash}
                  className="h-4 w-4"
                />
              </button>
            </div>
          </div>

          <div>
            <label className="block text-sm font-medium text-ink-700 mb-1">
              Confirm Password
            </label>

            <div className="relative">
              <input
                required
                minLength={8}
                type={showConfirmPassword ? "text" : "password"}
                value={confirmPassword}
                onChange={(e) => setConfirmPassword(e.target.value)}
                className="input-field pr-12"
              />

              <button
                type="button"
                onClick={() =>
                  setShowConfirmPassword((prev) => !prev)
                }
                className="absolute right-3 top-1/2 -translate-y-1/2 text-ink-500 hover:text-ink-800 transition-colors"
                aria-label={
                  showConfirmPassword
                    ? "Hide confirm password"
                    : "Show confirm password"
                }
              >
                <FontAwesomeIcon
                  icon={showConfirmPassword ? faEye : faEyeSlash}
                  className="h-4 w-4"
                />
              </button>
            </div>

            {confirmPassword &&
              password !== confirmPassword && (
                <p className="mt-1 text-sm text-clay-600">
                  Passwords do not match.
                </p>
              )}
          </div>

          <label className="flex items-start gap-2 text-sm text-ink-700">
            <input
              type="checkbox"
              checked={acknowledged}
              onChange={(e) => setAcknowledged(e.target.checked)}
              className="mt-1"
            />

            <span>
              I understand I shouldn't share my phone number or exact location,
              and that this is peer support, not therapy.
            </span>
          </label>

          {error && (
            <p className="text-clay-600 text-sm">
              {error}
            </p>
          )}

          <button
            type="submit"
            disabled={
              loading ||
              !password ||
              !confirmPassword ||
              password !== confirmPassword
            }
            className="btn-primary w-full"
          >
            {loading ? "Creating account…" : "Create account"}
          </button>
        </form>

        <div className="mt-6 text-center text-sm text-ink-600">
          Already have an account?{" "}
          <Link
            href="/login"
            className="text-ink-900 font-medium hover:underline"
          >
            Sign in
          </Link>
        </div>
      </div>
    </main>
  );
}